### ISSUE TITLE
Feature: Increase maximum possible price

### ISSUE THREAD

**Issue by stevebrownlee** [day-cohort-70/bangazon-api-i-like-planes-api#14]
The system currently will reject any product being created with a price greater than $10,000. Increase that maximum to $17,500.

**Comment by Sydney-M-Sharp** [comment]
resolved in pull request #16

**Comment by Sydney-M-Sharp** [comment]
resolved Feature Max Price Increase #72

**Comment by Sydney-M-Sharp** [comment]
resolving additional issues with creating a new product
