### ISSUE TITLE
Feature: User should be able to filter products by price

### ISSUE THREAD

**Issue by stevebrownlee** [day-cohort-70/bangazon-api-i-like-planes-api#31]
**Given** a user has clicked the **Filter Products** button on the product list view
**When** the user enters a number in the _Minimum Price_ field
**And** clicks the **Filter** button
**Then** the product list should be filtered to products whose prices are that value or higher

**Comment by Sydney-M-Sharp** [comment]
[Product Price filter#63](https://github.com/day-cohort-70/bangazon-api-i-like-planes-api/pull/63)

resolved in relation to previous pull request and related ticket

**Comment by Sydney-M-Sharp** [comment]
also related 
Feature: Get list of products over a specified price
[#12](https://github.com/day-cohort-70/bangazon-api-i-like-planes-api/issues/12)

Front end and back end work completed at the same time.
