### ISSUE TITLE
Bug: Can't remove an item from the cart

### ISSUE THREAD

**Issue by stevebrownlee** [day-cohort-70/bangazon-api-i-like-planes-api#8]
Customers are complaining that they can't remove an item from the cart after it has been added.

When the client performs a DELETE request to the `/lineitems/n` resource, it should remove the specified item from the user's cart.

**Comment by Sydney-M-Sharp** [comment]
Front end fetch request did not match the back end endpoint . Front end function adjustment made to match.

**Comment by Sydney-M-Sharp** [comment]
resolved .
